### ISSUE TITLE
Add an open-source license

### ISSUE THREAD

**Issue by exuanbo** [nano-metro-lab/nano-metro#1]
Possible candidates:

- [MIT](https://choosealicense.com/licenses/mit/)
- [GPL 3.0](https://choosealicense.com/licenses/gpl-3.0/)

More choices:

- <https://choosealicense.com/licenses/>
- <https://opensource.org/licenses/category>

**Comment by grepmorecat** [comment]
Personal suggestion is [GNU AGPLv3](https://choosealicense.com/licenses/agpl-3.0/). And credits to [Dinosaur Polo Club](https://dinopoloclub.com/) should be included in our source code.

My point is that, since this is only a school project which is highly inspired by Mini Metro, we really don't want it be abused by others. Learning-purpose and contributions should be fully welcomed, but for commercial use? Not sure about that.

Or should we consider [Commons Clause](https://commonsclause.com/) over GPL? Though it seems to be not so free...
<https://directory.fsf.org/wiki/License:Commons-Clause>
